title: "DNX Research Corporation"              # Site title in default language

description: ""        # A short description in default language

url: "" # The full URL to your site. 
                       # Note: site.github.url will be used by default.
  
author: Macleod       # Global author information, should be the
                       # key of file: _data/authors.yml to be used in
                       # site.data.authors[author]

twitter:
  username: DNXResearch   # site-wide Twitter handle

logo:                  # /assets/img/your-company-logo.png - URL to a site-wide logo (e.g., /)


permalink: /:categories/:year/:month/:day/:title

exclude:
  - vendor
  - deploy.sh
  - node_modules
  - Makefile
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - packages.json
